const path = require('path')
const PrerenderSPAPlugin = require('prerender-spa-plugin');
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer;

module.exports = {
    configureWebpack: {
      plugins: [
        new PrerenderSPAPlugin({
            staticDir: path.join(__dirname, 'dist'),
            routes: ['/',
            //'/artigos', 
            //'/sobre',
            //'/contato',
            //'/categorias/3',
            //'/desbloqueando-a-escrita',
            '/artigo/sinopse-que-chama-atencao',
            '/artigo/como-preparar-o-seu-livro-para-autopublicacao-parte-2',
            '/artigo/como-preparar-o-seu-livro-para-autopublicacao-parte-1',
            '/artigo/onde-publicar-sua-historia',
            '/artigo/as-cinco-etapas-da-revisao-parte-2',
            '/artigo/as-cinco-etapas-da-revisao-parte-1',
            '/artigo/mudancas-e-reacao-das-personagens',
            '/artigo/o-ponto-sem-retorno',
            '/artigo/como-lidar-com-exposicao-em-narrativas',
            '/artigo/dialogos-naturais',
            '/artigo/exposicao-como-decidir-o-que-entra-e-o-que-nao-entra-na-sua-historia',
            '/artigo/experiencia-nanowrimo-semana-4',
            '/artigo/as-4-mais-importantes-licoes-de-escrita-que-aprendi-em-2017-thiago',
            '/artigo/as-5-mais-importantes-licoes-de-escrita-que-aprendi-em-2017',
            '/artigo/experiencia-no-nanowrimo-semana-3',
            '/artigo/metas-do-escritor-para-2018',
            '/artigo/in-media-res-e-eucatastrofe',
            '/artigo/experiencia-no-nanowrimo-semana-2',
            '/artigo/7-livros',
            '/artigo/cliffhanger',
            '/artigo/como-expor',
            '/artigo/save-the-cat-pet-the-dog-e-lampshading',
            '/artigo/macguffin-deus-ex-machina-e-chekhovs-gun',
            '/artigo/usando-saltos-temporais-na-sua-historia',
            '/artigo/foreshadowing-red-herring-flashback',
            '/artigo/dicas-para-escrever-bons-misterios',
            '/artigo/dicas-para-turbinar-os-conflitos',
            '/artigo/comeco-dos-comecos',
            '/artigo/experiencia-no-nanowrimo-semana-1',
            '/artigo/tipos-de-conflito-em-narrativas',
            '/artigo/escrevendo-um-final-que-se-encaixa',
            '/artigo/como-usar-arquetipos-para-criar-e-desenvolver-personagens',
            '/artigo/planejando-o-planejamento',
            '/artigo/thiago-devecque',
            '/artigo/gustavo-avila',
            '/artigo/tecnicas-de-produtividade-para-escrever-mais-e-preparar-se-para-o-nanowrimo',
            '/artigo/revisao-perguntas',
            '/artigo/jornada-do-escritor',
            '/artigo/nanowrimo-prep',
            '/artigo/como-lidar-com-as-insegurancas-na-hora-de-escrever',
            '/artigo/voz-personagens',
            '/artigo/como-construir-o-seu-proprio-mundo',
            '/artigo/coisas-proposito',
            '/artigo/como-colocar-o-cenario-nas-paginas-do-seu-livro',
            '/artigo/revisao-cortando-10-do-seu-livro',
            '/artigo/construcao-de-cenario',
            '/artigo/scrivener-motivos',
            '/artigo/como-melhorar-suas-descricoes',
            '/artigo/como-dar-e-receber-criticas',
            '/artigo/os-beneficios-de-um-grupo-de-escrita',
            '/artigo/softwares-de-escrita-que-voce-ja-conhece-e-alguns-que-voce-deveria-conhecer',
            '/artigo/criar-personagens-profundas-e-coerentes',
            '/artigo/por-que-pensar-em-softwares-para-escrever-ficcao',
            '/artigo/o-caminho-da-escrita-9-licoes-de-um-samurai-aplicadas-arte-de-escrever',
            '/artigo/luciano-teixeira',
            '/artigo/como-expandir-as-fronteiras-de-sua-mente-criativa',
            '/artigo/4-maneiras-de-escrever-cenas-de-acao',
            '/artigo/as-barreiras-que-retem-a-sua-criatividade',
            '/artigo/elements-of-style',
            '/artigo/como-escrever-um-livro',
            '/artigo/diego-schutt',
            '/artigo/como-escrever-personagens-diferentes',
            '/artigo/writing-prompts',
            '/artigo/como-ser-mais-produtivo-enquanto-escreve-um-livro',
            '/artigo/bloqueio-de-escritor',
            '/artigo/coisas-personagens',
            '/artigo/generos-literarios-e-afins',
            '/artigo/rodrigo-van-kampen',
            '/artigo/diferenca-entre-forma-e-roteiro',
            '/artigo/como-escrever-um-livro-esqueca-o-outline',
            '/artigo/comece-com-o-outline',
            '/artigo/laura-bacellar',
            '/artigo/quando-comecar-a-escrever-o-seu-livro',
            '/artigo/um-pais-onde-escrever-nao-e-levado-a-serio',
            '/artigo/tornar-se-um-profissional',
            '/artigo/por-que-o-escritor-deve-ler',
            '/artigo/habito-de-escrever',
            '/artigo/sites-sobre-escrita-e-ficcao',
            '/artigo/coisas-que-voce-deve-fazer-quando-escreve-uma-historia',
            '/artigo/comecar-a-escrever-sem-inspiracao',
            '/artigo/quando-contar-e-quando-mostrar'
            ],
            renderer: new Renderer({
              injectProperty: '__PRERENDER_INJECTED',
              inject: {
                prerendered: true
              },
              maxConcurrentRoutes: 4,
              renderAfterElementExists: '.content-ready'
              //renderAfterDocumentEvent: 'render-event'
            })
          })
      ]
    }
  }